"use client"
import localFont from "next/font/local";
import "./globals.css";
import Header from "./component/Header/Header";
import Footer from "./component/Footer/Footer";
import {  useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Agicent App",
//   description: "Generated by Rajat Kumar",
// };

export default function RootLayout({ children }) {
  const router= usePathname()
  const initialShow = useMemo(() => router === "/", [router]);
  const[show,setShow]=useState(initialShow)
  
  console.log(router);
  useEffect(() => {
    setShow(router === "/");
  }, [router]);
  
  
  return (
    <html lang="en">
      <body>
        {show && <Header/> }
        
        {children}
        {show && <Footer/> }
        
      </body>
    </html>
  );
}
